// <auto-generated />
using System;
using ForgeHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForgeHub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250725114530_BaseMigration")]
    partial class BaseMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForgeHub.Models.FinalizedQuotation", b =>
                {
                    b.Property<int>("FinalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinalId"));

                    b.Property<DateTime?>("FinalizedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuotationId")
                        .HasColumnType("int");

                    b.Property<int>("RFQId")
                        .HasColumnType("int");

                    b.HasKey("FinalId");

                    b.HasIndex("QuotationId")
                        .IsUnique();

                    b.HasIndex("RFQId")
                        .IsUnique();

                    b.ToTable("FinalizedQuotations");
                });

            modelBuilder.Entity("ForgeHub.Models.RFQ", b =>
                {
                    b.Property<int>("RFQId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RFQId"));

                    b.Property<DateTime?>("BidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDateofBid")
                        .HasColumnType("datetime2");

                    b.Property<string>("FactoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndentNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFQLineNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFQNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReqDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReqQty")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RFQId");

                    b.HasIndex("UserId");

                    b.ToTable("RFQs");
                });

            modelBuilder.Entity("ForgeHub.Models.RFQQuotation", b =>
                {
                    b.Property<int>("QuotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuotationId"));

                    b.Property<string>("BidNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("QuotedAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RFQId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("QuotationId");

                    b.HasIndex("RFQId");

                    b.HasIndex("VendorId");

                    b.ToTable("RFQQuotations");
                });

            modelBuilder.Entity("ForgeHub.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFirstTimeLogin")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ForgeHub.Models.VendorRFQMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RFQId")
                        .HasColumnType("int");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RFQId");

                    b.HasIndex("VendorId");

                    b.ToTable("RFQVendors");
                });

            modelBuilder.Entity("ForgeHub.Models.FinalizedQuotation", b =>
                {
                    b.HasOne("ForgeHub.Models.RFQQuotation", "RFQQuotation")
                        .WithOne("FinalizedQuotation")
                        .HasForeignKey("ForgeHub.Models.FinalizedQuotation", "QuotationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForgeHub.Models.RFQ", "RFQ")
                        .WithOne("FinalizedQuotation")
                        .HasForeignKey("ForgeHub.Models.FinalizedQuotation", "RFQId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RFQ");

                    b.Navigation("RFQQuotation");
                });

            modelBuilder.Entity("ForgeHub.Models.RFQ", b =>
                {
                    b.HasOne("ForgeHub.Models.User", "users")
                        .WithMany("RFQs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("ForgeHub.Models.RFQQuotation", b =>
                {
                    b.HasOne("ForgeHub.Models.RFQ", "RFQ")
                        .WithMany("RFQQuotations")
                        .HasForeignKey("RFQId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForgeHub.Models.User", "Vendor")
                        .WithMany("RFQQuotations")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RFQ");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ForgeHub.Models.VendorRFQMapping", b =>
                {
                    b.HasOne("ForgeHub.Models.RFQ", "RFQ")
                        .WithMany("RFQVendors")
                        .HasForeignKey("RFQId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForgeHub.Models.User", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RFQ");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ForgeHub.Models.RFQ", b =>
                {
                    b.Navigation("FinalizedQuotation")
                        .IsRequired();

                    b.Navigation("RFQQuotations");

                    b.Navigation("RFQVendors");
                });

            modelBuilder.Entity("ForgeHub.Models.RFQQuotation", b =>
                {
                    b.Navigation("FinalizedQuotation")
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeHub.Models.User", b =>
                {
                    b.Navigation("RFQQuotations");

                    b.Navigation("RFQs");
                });
#pragma warning restore 612, 618
        }
    }
}
